sauce_username: msgpack-lite
sauce_key: "32947ef3-a727-4848-9aee-cebe65df3be4"
name: msgpack-lite
ui: mocha-bdd
html: "test/zuul/ie.html"
scripts:
  - "dist/msgpack.min.js"
browsers:
  - name: ie
    version: "9..latest"
  - name: chrome
    version: "latest"
  - name: firefox
    version: "latest"
  - name: safari
    version: "latest"
  - name: iphone
    version: ["8.4", "9.3", "10.3..latest"]
  - name: android
    version: ["4.4", "5.1", "6.0..latest"]
